clf : 'SVM'
clf_args:
  hidden_layer_size: [200,100,50]
  max_iter: 500
  k-fold: 2
  kernel: 'linear'
num_workers: 1
hparams: 
    superclass: 20
    subclass: 100
    arch: 'resnet18'
    arch_type: 'cifar_resnet'
    batch_size: 64
    optimizer: 
      type: 'sgd'
      momentum: 0.9
      weight_decay: 5.0E-4
    training: 
      epochs: 35
      lr: 0.5
      lr_scheduler: 
          type: 'cyclic'
          lr_peak_epoch: 5    
      # optimizer:  
    tuning:
      epochs: 15
      lr: 0.1
      lr_scheduler: 
          type: 'cyclic'
          lr_peak_epoch: 5  
          # type: 'ReduceLROnPlateau'
          # patience: 3
    # 'epochs': 20, 'lr': 0.5,
    # 'lr_scheduler':{'type': 'step_lr', 'step_size': 7,'gamma':0.5},   
data: 
  std_real: [68.209,65.431,70.459]
  mean_real: [129.377,124.106,112.478]
  mean: [125.307, 122.961, 113.8575] #come from CIFAR-10
  std: [51.5865, 50.847, 51.255]
  ds_root: '/home/yiwei/data/'
  ratio: 
    train_size : 0.3
    val_size : 0.2
    market_size : 0.5
    remove_rate: 0.9           
  acquired_num_per_class: []
  label_map:
    0: 0
    1: 1
  remove_fine_labels: [4]
  target_test_label: [4, 30, 55, 72, 95] # new + old distribution for a class
  old_test_label: [30, 55, 72, 95] # old distribution for a class
  train_label: [4, 30, 55, 72, 95, 1, 32, 67, 73, 91] # all classes
base_root: 'model/'