clf : 'SVM'
clf_args:
  hidden_layer_size: [200,100,50]
  max_iter: 500
  k-fold: 2
  kernel: 'linear'
num_workers: 1
hparams: 
    superclass: 20
    subclass: 100
    arch: 'resnet18'
    arch_type: 'cifar_resnet'
    batch_size: 64
    optimizer: 
      type: 'sgd'
      momentum: 0.9
      weight_decay: 5.0E-4
    training: 
      epochs: 35
      lr: 0.5
      lr_scheduler: 
          type: 'cyclic'
          lr_peak_epoch: 5    
      # optimizer:  
    tuning:
      epochs: 15
      lr: 0.1
      lr_scheduler: 
          type: 'cyclic'
          lr_peak_epoch: 5  
          # type: 'ReduceLROnPlateau'
          # patience: 3
    # 'epochs': 20, 'lr': 0.5,
    # 'lr_scheduler':{'type': 'step_lr', 'step_size': 7,'gamma':0.5},   
data: 
  std_real: [68.209,65.431,70.459]
  mean_real: [129.377,124.106,112.478]
  mean: [125.307, 122.961, 113.8575] #come from CIFAR-10
  std: [51.5865, 50.847, 51.255]
  ds_root: '/home/yiwei/data/'
  ratio: 
    train_size : 0.5
    val_size : 0.1
    market_size : 0.4
    remove_rate: 1.00           
  acquired_num_per_class: [100, 200, 300, 400]
  label_map:
    18: 0
    19: 1
  remove_fine_labels: [58, 90]
  target_test_label: [8, 13, 48, 58, 90] # new + old distribution for a class
  train_label: [8, 13, 48, 58, 90, 41, 69, 81, 85, 89] # all classes
base_root: 'model/'