clf : 'SVM'
clf_args:
  hidden_layer_size: [200,100,50]
  max_iter: 500
  k-fold: 2
  kernel: 'linear'
num_workers: 1
hparams: 
    superclass: 1
    subclass: 100
    # arch: 'resnet18'
    # arch_type: 'cifar_resnet'
    arch: 'squeezenet'
    arch_type: 'other'
    batch_size: 

      base: 64
      new: 32

      # base: 128
      # new: 64

    optimizer: 
      type: 'sgd'
      momentum: 0.9
      weight_decay: 5.0E-4
    training: 
      epochs: 10
      lr: 0.1
      lr_scheduler: 
          # type: 'step'
          type: 'cyclic'
          lr_peak_epoch: 5    
          # type: 'ReduceLROnPlateau'
          # patience: 5
    tuning:
      epochs: 10
      lr: 0.1
      lr_scheduler: 
          type: 'cyclic'
          lr_peak_epoch: 5  
          # type: 'ReduceLROnPlateau'
          # patience: 5
    # 'epochs': 20, 'lr': 0.5,
    # 'lr_scheduler':{'type': 'step_lr', 'step_size': 7,'gamma':0.5},   

data: 
  # std: [68.209,65.431,70.459]
  # mean: [129.377,124.106,112.478]
  # mean: [125.307, 122.961, 113.8575] #come from CIFAR-10
  # std: [51.5865, 50.847, 51.255]
  ds_root: '/home/yiwei/data/'
  ratio: 
    train_size : 0.4
    market_size : 0.6
    remove_rate: 
      train: 1.0
      test: null
      market: null
  # n_new_data: [100, 300, 500, 700, 900, 1100]
  # n_new_data: [1000, 1500, 2000, 2500, 3000]
  # n_new_data: [100, 400, 700, 1000, 1500]
  # n_new_data: [100, 400, 700, 1000]
  n_new_data: [100, 400, 700]

  remove_fine_labels: 
    c0: []
    c05: [88, 97, 34, 63]
    c00: [97, 34]
    c01: [43, 88, 97, 34, 63, 64]
    c02: [42, 43, 88, 97, 34, 63, 64, 66]

    c03: [3, 97, 34, 63]
    c04: [97, 34]

    c1: []
    c10: [81,90]
    c11: [48, 58, 90, 81, 85, 89]
    c12: [81, 90]
    c13: [81, 90, 48, 69]
    c14: [81, 90, 48, 69, 8, 41, 58, 89]
    c15: [81, 90, 48, 69, 58, 89]

    c2: [4, 73, 54, 10, 51, 40, 84, 18, 3, 12, 33, 38, 64, 45, 2, 44, 80, 96, 13, 81]

    c3: []
    c30: [97, 34, 38, 80]
    c31: [3, 97, 34, 64, 74, 80, 21, 38]
    c32: [3, 97, 42, 34, 64, 66, 74, 80, 65, 21, 38, 19]
    c33: [3, 97, 42, 34, 64, 66, 74, 80, 65, 21, 38, 19]

  cover_labels:

    c03:
      src: [88, 42, 66, 75, 43, 64]
      target: [3, 97, 34, 63, 43, 64]

    c04:
      src: [88, 75, 43, 64, 63, 3, 66, 42]
      target: [97, 34, 43, 64, 63, 3, 66, 42]

    c12:
      src: [13, 85, 8, 48, 58, 41, 69, 89]
      target: [81, 90, 8, 48, 58, 41, 69, 89]

    c13:
      src: [13, 85, 8, 41, 58, 89]
      target:  [81, 90, 48, 69, 58, 89]

    c14:
      src: [13, 85]
      target: [13, 85, 81, 90]

    c15:
      src: [13, 85, 8, 41]
      target: [81, 90, 8, 41]

  total_labels:
    c0:
      label_map:
        8: 0
        12: 1
      select_fine_labels: [3, 42, 43, 88, 97, 34, 63, 64, 66, 75] # superclass animals
    
    c1:
      label_map:
        18: 0
        19: 1
      select_fine_labels: [8, 13, 48, 58, 90, 41, 69, 81, 85, 89] # superclass vehicles

    c2:
      label_map: []
      select_fine_labels: []
      
    c3:
      label_map:
        8: 0
        12: 1
        11: 2
        16: 3
      select_fine_labels: [3, 42, 43, 88, 97, 34, 63, 64, 66, 75, 15, 19, 21, 31, 38, 36, 50, 65, 74, 80] 

base_root: 'model/'