clf : 'SVM'
clf_args:
  hidden_layer_size: [200,100,50]
  max_iter: 500
  k-fold: 2
  kernel: 'linear'
num_workers: 1
hparams: 
    superclass: 20
    subclass: 100
    arch: 'resnet18'
    arch_type: 'cifar_resnet'
    batch_size: 
      base: 64
      new: 20
    optimizer: 
      type: 'sgd'
      momentum: 0.9
      weight_decay: 5.0E-4
    training: 
      epochs: 35
      lr: 0.5
      lr_scheduler: 
          type: 'cyclic'
          lr_peak_epoch: 5    
      # optimizer:  
    tuning:
      epochs: 15
      lr: 0.1
      lr_scheduler: 
          type: 'cyclic'
          lr_peak_epoch: 5  
          # type: 'ReduceLROnPlateau'
          # patience: 3
    # 'epochs': 20, 'lr': 0.5,
    # 'lr_scheduler':{'type': 'step_lr', 'step_size': 7,'gamma':0.5},   
data: 
  std_real: [68.209,65.431,70.459]
  mean_real: [129.377,124.106,112.478]
  mean: [125.307, 122.961, 113.8575] #come from CIFAR-10
  std: [51.5865, 50.847, 51.255]
  ds_root: '/home/yiwei/data/'
  ratio: 
    train_size : 0.4
    val_size : 0.2
    market_size : 0.4
    remove_rate: 1.00           
  # n_new_data: [200, 300, 400, 500, 600]
  n_new_data: [100, 200, 300, 400]
  label_map:
    8: 0
    12: 1
  remove_fine_labels: [97, 34]
  train_label: [3, 42, 43, 88, 97, 34, 63, 64, 66, 75] # superclass animals
  # remove_fine_labels: [81,90]
  # train_label: [8, 13, 48, 58, 90, 41, 69, 81, 85, 89] # superclass vehicles
  
  # ratio: 
  #   train_size : 0.1
  #   val_size : 0.6
  #   market_size : 0.3
  #   remove_rate: 1.00           
  # n_new_data: []
  # label_map:
  #   3: 1
  #   42: 1
  #   43: 1
  #   88: 1
  #   97: 0
  #   34: 0
  #   63: 1
  #   64: 1
  #   66: 1
  #   75: 1
  # remove_fine_labels: []
  # train_label: [3, 42, 43, 88, 97, 34, 63, 64, 66, 75] # superclass vehicles

base_root: 'model/'