detector : 'SVM'
detector_args:
  hidden_layer_size: [200,100,50]
  max_iter: 500
  k-fold: 2
  kernel: 'linear'
num_workers: 1
hparams: 
  source:
    sessions: 11
    superclass: 10
    subclass: 50
    arch: 'squeezenet'
    arch_type: 'raw'
    batch_size: 
      base: 128
      new: 64
    optimizer: 
      type: 'sgd'
      momentum: 0.9
      weight_decay: 5.0E-4
    training: 
      epochs: 20
      lr: 0.1
      lr_scheduler: 
          # type: 'step'
          type: 'cyclic'
          lr_peak_epoch: 10    
          # type: 'ReduceLROnPlateau'
          # patience: 5
  padding:
    sessions: 11
    superclass: 10
    subclass: 50
    arch: 'squeezenet'
    arch_type: 'raw'
    batch_size: 
      base: 128
      new: 64
    optimizer: 
      type: 'sgd'
      momentum: 0.9
      weight_decay: 5.0E-4
    training: 
      epochs: 20
      lr: 0.1
      lr_scheduler: 
          # type: 'step'
          type: 'cyclic'
          lr_peak_epoch: 10    
          # type: 'ReduceLROnPlateau'
          # patience: 5

data: 
  root: 'data/core.pkl'
  ratio: 
    train : 0.3
    market : 0.7
    test: 0.1
    val_from_test: 0.5
    remove: 
      new_labels: 1.0
      old_labels: null
  budget: [1500, 1800, 2100, 2500, 3000, 3500] # 1890 shifted data in the market
  #
  #
  seq: 
    budget: null 
    n_rounds: 2 #seq
  labels:
    remove:
      object: []
      session: [2, 6] #Three of the eleven sessions (#3, #7 and #10) have been selected for test and the remaining 8 sessions are used for training.

    map: null
  
base_root: 'model/'