detector : 'SVM'
detector_args:
  hidden_layer_size: [200,100,50]
  max_iter: 500
  k-fold: 2
  kernel: 'linear'
num_workers: 1
base_type: 'cnn'
padding_type: 'cnn'
hparams:
  optimal: 
      sessions: 11
      superclass: 10
      subclass: 50
      arch: 'squeezenet'
      arch_type: 'raw'
      batch_size: 
        base: 128
        new: 64
      optimizer: 
        type: 'sgd'
        momentum: 0.9
        weight_decay: 5.0E-4
      training: 
        epochs: 40
        lr: 0.1
        lr_scheduler: 
            # type: 'step'
            type: 'cyclic'
            lr_peak_epoch: 10    
            # type: 'ReduceLROnPlateau'
            # patience: 5
  source: 
      sessions: 11
      superclass: 10
      subclass: 50
      arch: 'squeezenet'
      arch_type: 'raw'
      batch_size: 
        base: 128
        new: 64
      optimizer: 
        type: 'sgd'
        momentum: 0.9
        weight_decay: 5.0E-4
      training: 
        epochs: 20
        lr: 0.1
        lr_scheduler: 
            # type: 'step'
            type: 'cyclic'
            lr_peak_epoch: 10    
            # type: 'ReduceLROnPlateau'
            # patience: 5
  padding: 
      sessions: 11
      superclass: 10
      subclass: 50
      arch: 'squeezenet'
      arch_type: 'raw'
      batch_size: 
        base: 128
        new: 64
      optimizer: 
        type: 'sgd'
        momentum: 0.9
        weight_decay: 5.0E-4
      training: 
        epochs: 20
        lr: 0.1
        lr_scheduler: 
            # type: 'step'
            type: 'cyclic'
            lr_peak_epoch: 10    
            # type: 'ReduceLROnPlateau'
            # patience: 5

data: 
  root: 'data/core.pkl'

  ratio: 
    remove: 
      new_labels: 1.0
      old_labels: null
  budget: [1500, 1800, 2100, 2500, 3000, 3500]
  #[2500, 3000, 3500]
#  [1500, 1800, 2100, 2500, 3000, 3500]
  seq: 
    budget: null #300 # seq_1
    n_rounds: 2 #seq
  labels:
    remove:
      object: [0,5,10,20,30,40,15,25,35,45]
      session: []
    map: null
  
base_root: 'model/'